services:
  django:
    build: .
    container_name: django
    entrypoint: /app/entrypoint.sh
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles
      - gunicorn_socket:/run/gunicorn
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: always

  nginx:
    image: nginx:1.28.3-alpine
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - media_data:/media
      - static_data:/staticfiles
      - gunicorn_socket:/run/gunicorn
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - django
    restart: always

  postgres:
    image: postgres:17.9
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  redis:
    image: redis:8.6.2-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    restart: always

  celery:
    build: .
    container_name: celery
    command: celery -A core worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

volumes:
  media_data:
  static_data:
  redis_data:
  postgres_data:
  gunicorn_socket:
