# Generated by Django 5.2.15 on 2026-07-19 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código do Cupom')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Desconto')),
                ('discount_type', models.CharField(choices=[('FIXED', 'Fixo'), ('PERCENTAGE', 'Porcentagem')], max_length=20, verbose_name='Tipo de desconto')),
                ('maximum_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Máximo de Usos')),
                ('total_uses', models.PositiveIntegerField(default=0, verbose_name='Total de Usos')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('activation_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de ativação')),
                ('deactivation_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de desativação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'cupom',
                'verbose_name_plural': 'cupons',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('cycle', models.CharField(choices=[('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUALLY', 'Semestral'), ('ANNUALLY', 'Anual')], max_length=20, verbose_name='Ciclo')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('free_period', models.PositiveIntegerField(default=0, verbose_name='Período Gratuito')),
                ('refund_period', models.PositiveIntegerField(default=7, verbose_name='Período de Reembolso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True, verbose_name='Código do Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=50, unique=True, verbose_name='Código da Assinatura')),
                ('pix_authorization_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Autorização do Pix Automático')),
                ('pix_conciliation_identifier', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Identificador de Conciliação do Pix Automático')),
                ('credit_card_token', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Autorização do Cartão de Crédito')),
                ('billing_type', models.CharField(choices=[('PIX', 'Pix'), ('CREDIT_CARD', 'Cartão de Crédito')], max_length=20, verbose_name='Tipo de Cobrança')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa')], default='INACTIVE', max_length=20, verbose_name='Status')),
                ('next_due', models.DateField(blank=True, null=True, verbose_name='Próximo Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.coupon', verbose_name='Cupom')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='billing.customer', verbose_name='Código do Cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=50, unique=True, verbose_name='Código da Cobrança')),
                ('billing_type', models.CharField(choices=[('PIX', 'Pix'), ('CREDIT_CARD', 'Cartão de Crédito')], max_length=20, verbose_name='Tipo de Cobrança')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('RECEIVED', 'Recebido'), ('OVERDUE', 'Vencido'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20, verbose_name='Status da Cobrança')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.customer', verbose_name='Código do Cliente')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscription', verbose_name='Código da Assinatura')),
            ],
            options={
                'verbose_name': 'cobrança',
                'verbose_name_plural': 'cobranças',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa')], max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_histories', to='billing.plan', verbose_name='Plano')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_histories', to='billing.subscription', verbose_name='Código da Assinatura')),
            ],
            options={
                'verbose_name': 'histórico de assinatura',
                'verbose_name_plural': 'histórico de assinaturas',
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(max_length=50, unique=True, verbose_name='Código do Webhook')),
                ('event', models.CharField(db_index=True, max_length=50, verbose_name='Evento')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='billing.customer', verbose_name='Código do Cliente')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='billing.subscription', verbose_name='Código da Assinatura')),
            ],
            options={
                'verbose_name': 'webhook',
                'verbose_name_plural': 'webhooks',
            },
        ),
    ]
