# Generated by Django 5.2.17 on 2026-08-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_subscriptionhistory_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
